package com.youcheyihou.testgreendao.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.youcheyihou.testgreendao.database.bean.Bean;

import com.youcheyihou.testgreendao.database.dao.BeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig beanDaoConfig;

    private final BeanDao beanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        beanDaoConfig = daoConfigMap.get(BeanDao.class).clone();
        beanDaoConfig.initIdentityScope(type);

        beanDao = new BeanDao(beanDaoConfig, this);

        registerDao(Bean.class, beanDao);
    }
    
    public void clear() {
        beanDaoConfig.getIdentityScope().clear();
    }

    public BeanDao getBeanDao() {
        return beanDao;
    }

}
